# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.SlugField(default='trash', max_length=100),
            preserve_default=False,
        ),
    ]
