# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_team_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
