# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_auto_20170802_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='slug',
            field=models.SlugField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chore',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='reminder.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roommate',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
