# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_auto_20170803_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='roommate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='reminder.Roommate'),
        ),
    ]
